# Generated by Django 5.0.4 on 2024-06-20 19:43

import eduviz.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=100, validators=[eduviz.validators.validate_senha])),
            ],
        ),
    ]
